spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/view/
  datasource:
    url: jdbc:mysql://localhost:3306/fsd
    username: root
    password: 1234
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl